[package]
name = "aes-rust"
version = "0.1.0"
authors = ["Sean Weaver"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"

[lib]
path = "src/lib.rs"
