name: Proofs

on: [push, pull_request]

jobs:
  run-kani-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Kani Rust Verifier
        uses: model-checking/kani-github-action@v0.13

  run-kani-terse:
    steps:
      - name: Install Rust
        uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: nightly-2022-10-11
          override: true

      - name: Install Kani
        shell: bash
        run: |
          export KANI_VERSION="0.13.0";
          cargo install --version $KANI_VERSION --locked kani-verifier;
          cargo-kani setup;

      - name: Checkout
        uses: actions/checkout@v2

      - name: Kani terse
        shell: bash
        run: cargo kani --output-format=terse
