name: Proofs

on: [push, pull_request]

jobs:
  run-kani:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Kani Rust Verifier
      uses: model-checking/kani-github-action@v0.13
